In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../generated-data/costanzo_gi")

In [11]:
df['pair'] = [tuple(sorted((a,b))) for a,b in zip(df['a'],df['b'])]

In [12]:
pairs = set(df[df['temp']==26]['pair'])
len(pairs)

3084707

In [13]:
pairs = set(df[df['temp']==30]['pair'])
len(pairs)

9431297

In [17]:
tdf = pd.read_csv("../generated-data/task_yeast_tgi")

In [18]:
tdf.shape

(74463, 7)

In [19]:
df = pd.read_csv("../generated-data/task_yeast_gi_hybrid")
split = np.load("../generated-data/splits/task_yeast_gi_hybrid_full.npz")

In [20]:
list(split.keys())

['train_sets', 'valid_sets', 'test_sets', 'reps', 'folds', 'valid_prop']

In [21]:
split['test_sets'].shape

(10, 4, 6918870)

In [23]:
tix = np.reshape(split['test_sets'], (40,-1))


In [24]:
cols = ["is_neutral", "rel_not_ppc", "rel_not_phospho", "rel_not_trans", "rel_not_complex", "rel_not_pathway"]

In [27]:
for test_ix in tix:
    sdf = df[test_ix]
    print(np.array(np.sum(1-sdf[cols], axis=0)))

[1385 1675   67 2343  178 9135]
[1118 1077   47 3851  242 8166]
[ 1446  2016    38  3118   241 10867]
[1410 1885   61 4267  196 9513]
[1272 1548   44 4672  223 9292]
[1302 1587   32 1835  164 8752]
[1469 1586   70 4033  232 8363]
[ 1200  1909    42  3001   231 11300]
[1191 1577   79 3596  239 8658]
[1286 1722   37 2944  234 8673]
[1370 1793   51 4639  246 9869]
[ 1340  1517    39  2240   170 10583]
[1446 1845   72 4321  177 8860]
[ 1472  1845    40  2882   153 10670]
[ 1086  1278    34  3080   335 10073]
[1312 1396   54 3183  209 8088]
[1114 1566   44 4160  179 8322]
[1024 1433   62 2597  187 9964]
[1696 1972   59 3797  318 9260]
[ 1440  1673    44  3108   217 10506]
[1290 1915   56 3050  193 8702]
[ 1541  1514    72  3856   186 11194]
[1277 1691   43 3735  269 9687]
[1263 1452   45 2854  241 8329]
[1252 1914   45 3984  229 8982]
[1280 1978   56 3132  265 8968]
[ 1493  1208    51  3218   195 11098]
[1320 1719   67 3168  188 8828]
[1481 1558   62 4170  185 9061]
[1441 1742   50 3512  23